In [2]:
import numpy as np

In [4]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
l = [1,2,3]
l

[1, 2, 3]

In [8]:
python_list = list(range(100))
python_list[:5]

[0, 1, 2, 3, 4]

In [12]:
import sys

sys.getsizeof(python_list[0])*len(python_list)

2800

In [18]:
numpy_array = np.arange(100)
numpy_array[:5]

array([0, 1, 2, 3, 4])

In [20]:
numpy_array.nbytes

400

In [24]:
l1 = [1,2,3]
l2 = [8,7,9]

tuple(zip(l1,l2))

for x, y in zip(l1, l2):
    print(x ,y)

1 8
2 7
3 9


In [28]:
import time 

SIZE = 1000000

l1 = list(range(SIZE))
l2 = list(range(SIZE))


start_time = time.time()
l3 = [x+y for x, y in zip(l1,l2)]
end_time = time.time()

print('Python list took:', end_time-start_time)

Python list took: 0.14635968208312988


In [37]:
n1 = np.arange(SIZE)
n2 = np.arange(SIZE)
n1[:4], n2[:4]

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [39]:
start_time = time.time()
n3 = n1+n2
end_time = time.time()
print('Python list took:', end_time-start_time)

Python list took: 0.009972333908081055


In [41]:
l1 = list(range(5))
l2 = list(range(5))
l1[:3], l2[:3]

([0, 1, 2], [0, 1, 2])

In [47]:
l1+l2

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [49]:
l3 = [x+y for x, y in zip(l1, l2)]
l3

[0, 2, 4, 6, 8]