In [2]:
import numpy as np

In [4]:
rev_q1 = np.array([10,12,9])
rev_q1.ndim

1

In [6]:
rev = np.array([[10 ,12 ,9], [15, 11, 13]])
rev.ndim

2

In [8]:
rev

array([[10, 12,  9],
       [15, 11, 13]])

In [12]:
rev[1,0]

15

In [39]:
rev[1,0] = 14
rev

array([[10, 12,  9],
       [14, 11, 13]])

In [41]:
rev.dtype

dtype('int32')

In [49]:
rev = np.array([[10,12,9],[15,11,13]], dtype=np.float64)
rev.dtype

dtype('float64')

In [51]:
rev.itemsize

8

In [53]:
rev.size

6

In [55]:
rev.shape

(2, 3)

In [57]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [61]:
np.sort(rev)

array([[ 9., 10., 12.],
       [11., 13., 15.]])

In [63]:
np.sort(rev, axis=None)

array([ 9., 10., 11., 12., 13., 15.])

In [65]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [67]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [75]:
np.arange(10,30,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [77]:
np.linspace(10, 20, 5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [79]:
np.linspace(10, 20, 20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [81]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [83]:
rev.flatten()

array([10., 12.,  9., 15., 11., 13.])

In [85]:
rev.min()

9.0

In [87]:
rev.max()

15.0

In [89]:
rev.sum(axis=1)

array([31., 39.])

In [91]:
for row in rev:
    print("row:_> ",row)

row:_>  [10. 12.  9.]
row:_>  [15. 11. 13.]


In [97]:
b = np.array([1,4,16])

In [99]:
np.sqrt(b)

array([1., 2., 4.])

In [101]:
np.square(b)

array([  1,  16, 256])

In [103]:
np.std(b)

6.48074069840786

In [106]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])