In [2]:
import numpy as np

In [4]:
a = np.array([6,7,8,9])

In [6]:
a[0:2]

array([6, 7])

In [8]:
a[2:]

array([8, 9])

In [10]:
a[-1]

9

In [12]:
a[-2]

8

In [16]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]
])

In [18]:
b[1,2]

6

In [20]:
b[2,0]

7

In [22]:
b[-1]

array([7, 8, 9])

In [24]:
b[-1,  0:2]

array([7, 8])

In [28]:
b[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [58]:
# Customer ID, Name
c = np.array([
    [101, 'Mira'],
    [102, 'Abdul'],
    [103, 'Andrea']
])

# Customer ID, Purchase Amount, Purchase Date
d = np.array([
    [101, 250.50, '2023-08-01'],
    [102, 150.00, '2023-08-02'],
    [103, 300.75, '2023-08-01']
])

In [60]:
np.hstack((c,d))

array([['101', 'Mira', '101', '250.5', '2023-08-01'],
       ['102', 'Abdul', '102', '150.0', '2023-08-02'],
       ['103', 'Andrea', '103', '300.75', '2023-08-01']], dtype='<U32')

In [62]:
c

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea']], dtype='<U11')

In [68]:
e = np.array([
    [104, 'Venkat'],
    [105, 'Jhon'],
    [106, 'Kathy']
])
e

array([['104', 'Venkat'],
       ['105', 'Jhon'],
       ['106', 'Kathy']], dtype='<U11')

In [70]:
np.vstack((c,e))

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea'],
       ['104', 'Venkat'],
       ['105', 'Jhon'],
       ['106', 'Kathy']], dtype='<U11')

In [82]:
transactions = np.array([
    [101, 'Mohan', 250.50, '2023-08-01'],
    [102, 'Bob', 150.00, '2023-08-02'],
    [103, 'Fatima', 300.75, '2023-08-01'],
    [104, 'David', 400.20, '2023-08-03'],
    [105, 'Aryan', 330.1, '2023-08-04'],
])

np.hsplit(transactions, [3])

[array([['101', 'Mohan', '250.5'],
        ['102', 'Bob', '150.0'],
        ['103', 'Fatima', '300.75'],
        ['104', 'David', '400.2'],
        ['105', 'Aryan', '330.1']], dtype='<U32'),
 array([['2023-08-01'],
        ['2023-08-02'],
        ['2023-08-01'],
        ['2023-08-03'],
        ['2023-08-04']], dtype='<U32')]

In [76]:
transactions = np.array([
    [101, 'Mohan', 250.50, '2023-08-01'],
    [102, 'Bob', 150.00, '2023-08-02'],
    [103, 'Fatima', 300.75, '2023-08-01'],
    [104, 'David', 400.20, '2023-08-03'],
    [105, 'Aryan', 330.1, '2023-08-04'],
])

a , b = np.hsplit(transactions, [3])

In [78]:
a

array([['101', 'Mohan', '250.5'],
       ['102', 'Bob', '150.0'],
       ['103', 'Fatima', '300.75'],
       ['104', 'David', '400.2'],
       ['105', 'Aryan', '330.1']], dtype='<U32')

In [80]:
b

array([['2023-08-01'],
       ['2023-08-02'],
       ['2023-08-01'],
       ['2023-08-03'],
       ['2023-08-04']], dtype='<U32')

In [88]:
np.vsplit(transactions, [4])

[array([['101', 'Mohan', '250.5', '2023-08-01'],
        ['102', 'Bob', '150.0', '2023-08-02'],
        ['103', 'Fatima', '300.75', '2023-08-01'],
        ['104', 'David', '400.2', '2023-08-03']], dtype='<U32'),
 array([['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')]

In [96]:
x , y = np.vsplit(transactions, [2])

In [98]:
x

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02']], dtype='<U32')

In [100]:
y

array([['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [102]:
monthly_sales = np.array([30, 33, 35, 28, 42])

result = monthly_sales < 32
result

array([ True, False, False,  True, False])

In [104]:
monthly_sales[result]

array([30, 28])

In [108]:
monthly_sales.max()

42

In [114]:
index = np.argmax(monthly_sales)
index

4

In [116]:
monthly_sales[index]

42

In [118]:
transactions

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')